# BookStack with MariaDB - Standalone deployment

services:
  # MariaDB for BookStack
  bookstack-db:
    image: mariadb:11
    container_name: mosaic-bookstack-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-${POSTGRES_PASSWORD}}
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-${POSTGRES_PASSWORD}}
    volumes:
      - /opt/mosaic/bookstack-db/data:/var/lib/mysql
    networks:
      mosaicstack-internal:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5

  # BookStack - Documentation (EXTERNAL + INTERNAL)
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: mosaic-bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://${BOOKSTACK_DOMAIN}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${MYSQL_PASSWORD:-${POSTGRES_PASSWORD}}
      - DB_DATABASE=bookstack
      - APP_KEY=${BOOKSTACK_APP_KEY}
    volumes:
      - /opt/mosaic/bookstack/data:/config
    ports:
      - "8080:80"     # Web interface
    networks:
      nginx-proxy-manager_default:  # External access
      mosaicstack-internal:         # Database access
    depends_on:
      bookstack-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status"]
      interval: 30s
      timeout: 10s
      retries: 5

# Networks
networks:
  # External network - create if doesn't exist
  nginx-proxy-manager_default:
    driver: bridge
    name: nginx-proxy-manager_default
  
  # Internal network for secure service communication
  mosaicstack-internal:
    driver: bridge
    internal: true
    name: mosaicstack-internal
    ipam:
      config:
        - subnet: 172.28.0.0/16