version: '3.8'

x-common-settings: &common-settings
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  # Prometheus - Metrics Collection
  prometheus:
    <<: *common-settings
    image: prom/prometheus:latest
    container_name: mosaic-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus-data:/prometheus
    networks:
      - mosaic-monitoring
    ports:
      - "9090:9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prometheus.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${METRICS_AUTH}"

  # Grafana - Visualization
  grafana:
    <<: *common-settings
    image: grafana/grafana:latest
    container_name: mosaic-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.${DOMAIN}
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,redis-datasource
      - GF_DATABASE_TYPE=sqlite3
      - GF_DATABASE_PATH=/var/lib/grafana/grafana.db
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info
      - GF_SMTP_ENABLED=${GRAFANA_SMTP_ENABLED:-false}
      - GF_SMTP_HOST=${EMAIL_HOST}:${EMAIL_PORT}
      - GF_SMTP_USER=${EMAIL_HOST_USER}
      - GF_SMTP_PASSWORD=${EMAIL_HOST_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${EMAIL_FROM}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - mosaic-monitoring
      - mosaic-proxy
    depends_on:
      - prometheus
      - loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # Loki - Log Aggregation
  loki:
    <<: *common-settings
    image: grafana/loki:latest
    container_name: mosaic-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./configs/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    networks:
      - mosaic-monitoring
    ports:
      - "3100:3100"

  # Promtail - Log Collection
  promtail:
    <<: *common-settings
    image: grafana/promtail:latest
    container_name: mosaic-promtail
    volumes:
      - ./configs/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mosaic-monitoring
    depends_on:
      - loki

  # Alertmanager - Alert Routing
  alertmanager:
    <<: *common-settings
    image: prom/alertmanager:latest
    container_name: mosaic-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://alerts.${DOMAIN}'
    volumes:
      - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    networks:
      - mosaic-monitoring
      - mosaic-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alerts.${DOMAIN}`)"
      - "traefik.http.routers.alertmanager.tls.certresolver=letsencrypt"
      - "traefik.http.routers.alertmanager.middlewares=auth"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"

  # Node Exporter - Host Metrics
  node-exporter:
    <<: *common-settings
    image: prom/node-exporter:latest
    container_name: mosaic-node-exporter
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - mosaic-monitoring
    ports:
      - "9100:9100"

  # cAdvisor - Container Metrics
  cadvisor:
    <<: *common-settings
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: mosaic-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - mosaic-monitoring
    ports:
      - "8080:8080"
    devices:
      - /dev/kmsg
    privileged: true

  # Postgres Exporter
  postgres-exporter:
    <<: *common-settings
    image: prometheuscommunity/postgres-exporter:latest
    container_name: mosaic-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable
    networks:
      - mosaic-monitoring
      - mosaic-db
    ports:
      - "9187:9187"

  # Redis Exporter
  redis-exporter:
    <<: *common-settings
    image: oliver006/redis_exporter:latest
    container_name: mosaic-redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - mosaic-monitoring
      - mosaic-cache
    ports:
      - "9121:9121"

  # Blackbox Exporter - Endpoint Monitoring
  blackbox-exporter:
    <<: *common-settings
    image: prom/blackbox-exporter:latest
    container_name: mosaic-blackbox-exporter
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    volumes:
      - ./configs/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    networks:
      - mosaic-monitoring
    ports:
      - "9115:9115"

networks:
  mosaic-monitoring:
    external: true
  mosaic-proxy:
    external: true
  mosaic-db:
    external: true
  mosaic-cache:
    external: true

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local
  alertmanager-data:
    driver: local